# Generated by Django 3.2.5 on 2022-01-06 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_alter_categories_super_category'),
        ('clients', '0002_auto_20220104_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='super_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client', to='categories.supercategory'),
        ),
    ]
