# Generated by Django 4.0.2 on 2022-02-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_clients_super_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='serial_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
