# Generated by Django 2.2.12 on 2021-12-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20211228_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('super_category_name', models.TextField()),
                ('slug', models.SlugField(editable=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SuperCategoryVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=254)),
                ('video_description', models.TextField()),
                ('video_link', models.CharField(max_length=254)),
                ('super_category', models.ManyToManyField(to='categories.SuperCategory')),
            ],
        ),
        migrations.CreateModel(
            name='CategoriesVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=254)),
                ('video_description', models.TextField()),
                ('video_link', models.CharField(max_length=254)),
                ('category', models.ManyToManyField(to='categories.Categories')),
            ],
        ),
    ]
