# Generated by Django 2.2.12 on 2021-12-28 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_categoriesvideo_supercategory_supercategoryvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='super_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='categories.SuperCategory'),
            preserve_default=False,
        ),
    ]
