# Generated by Django 2.2.12 on 2021-12-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_categories_super_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supercategory',
            name='super_category_name',
            field=models.CharField(max_length=254),
        ),
    ]
