# Generated by Django 2.2.12 on 2021-12-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_auto_20211229_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supercategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='supercategory',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, unique=True),
        ),
    ]
