# Generated by Django 3.2.5 on 2022-01-06 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_auto_20220104_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='super_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sp', to='categories.supercategory'),
        ),
    ]
