# Generated by Django 3.2.5 on 2022-01-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_alter_categories_super_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='super_category',
        ),
        migrations.AddField(
            model_name='categories',
            name='super_category',
            field=models.ManyToManyField(related_name='sp', to='categories.SuperCategory'),
        ),
    ]
