# Generated by Django 3.2.5 on 2022-02-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0011_auto_20220129_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='serial_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='YoutubeVideoLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_link', models.CharField(max_length=100)),
                ('category', models.ManyToManyField(related_name='yt_video', to='categories.Categories')),
            ],
        ),
    ]
