# Generated by Django 3.2.5 on 2022-02-02 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0013_auto_20220202_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtubevideolinks',
            old_name='category',
            new_name='super_category',
        ),
    ]
