# Generated by Django 3.2.5 on 2022-02-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0015_alter_youtubevideolinks_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideolinks',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hi'),
        ),
    ]
