# Generated by Django 4.0.2 on 2022-02-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0019_supercategory_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideolinks',
            name='serial_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
