# Generated by Django 4.0.2 on 2022-02-22 08:42

import categories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0020_youtubevideolinks_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='brief_youtube1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='brief_youtube2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='brief_youtube3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='heading_for_youtube',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='image_youtube1',
            field=models.ImageField(blank=True, null=True, upload_to=categories.models.content_file_name),
        ),
        migrations.AddField(
            model_name='categories',
            name='image_youtube2',
            field=models.ImageField(blank=True, null=True, upload_to=categories.models.content_file_name),
        ),
        migrations.AddField(
            model_name='categories',
            name='image_youtube3',
            field=models.ImageField(blank=True, null=True, upload_to=categories.models.content_file_name),
        ),
        migrations.AddField(
            model_name='categories',
            name='title_youtube1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='title_youtube2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='title_youtube3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='video_link_youtube1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='video_link_youtube2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='video_link_youtube3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
