# Generated by Django 4.0.2 on 2022-02-24 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0021_categories_brief_youtube1_categories_brief_youtube2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuperCategoryVideo',
        ),
    ]
