# Generated by Django 4.0.2 on 2022-03-02 06:09

import categories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0022_delete_supercategoryvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='landscapeImage',
            field=models.ImageField(blank=True, null=True, upload_to=categories.models.content_file_name),
        ),
    ]
