# Generated by Django 3.2.5 on 2022-05-17 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0024_categories_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MetaTags',
        ),
    ]
