# Generated by Django 3.2.5 on 2022-01-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecarousel',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
