# Generated by Django 3.2.5 on 2022-01-06 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_alter_categories_super_category'),
        ('home', '0002_alter_homecarousel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videoseeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='videoseeding')),
                ('supercategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videoseeding', to='categories.supercategory')),
            ],
        ),
    ]
