# Generated by Django 3.2.5 on 2022-01-11 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_auto_20220107_1844'),
        ('home', '0004_videocategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='home_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_desktop', models.ImageField(upload_to='home_image')),
                ('image_mobile', models.ImageField(upload_to='home_image')),
                ('supercategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_image', to='categories.supercategory')),
            ],
        ),
    ]
