# Generated by Django 3.2.5 on 2022-01-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_home_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='homePageHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='homePageHeadingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homepageheading')),
            ],
        ),
    ]
