# Generated by Django 3.2.5 on 2022-01-11 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepageheading_homepageheadingimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageheadingimage',
            name='homePageHeadingImage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='homePageHeadingImage', to='home.homepageheading'),
            preserve_default=False,
        ),
    ]
