# Generated by Django 3.2.5 on 2022-01-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_alter_categories_image'),
        ('home', '0007_homepageheadingimage_homepageheadingimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecarousel',
            name='image',
            field=models.ImageField(default=1, upload_to='homecarousel'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SubCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=254)),
                ('brief', models.CharField(max_length=254)),
                ('image', models.ImageField(upload_to='category')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('slug', models.SlugField(editable=False)),
                ('category', models.ManyToManyField(related_name='categories', to='categories.Categories')),
            ],
        ),
    ]
