# Generated by Django 3.2.5 on 2022-01-13 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_alter_categories_image'),
        ('home', '0008_auto_20220113_2356'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubCategorie',
            new_name='SubCategories',
        ),
    ]
