# Generated by Django 3.2.5 on 2022-01-21 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_subcategorie_subcategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('subtitle', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='aboutusteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='teamphoto')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('aboutus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamImage', to='home.aboutus')),
            ],
        ),
        migrations.CreateModel(
            name='aboutusattribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute', to='home.aboutus')),
            ],
        ),
    ]
