# Generated by Django 3.2.5 on 2022-01-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_aboutus_aboutusattribute_aboutusteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusattribute',
            name='discription',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutusattribute',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
