# Generated by Django 3.2.5 on 2022-01-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20220121_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='video',
            field=models.FileField(default=1, upload_to='abous-us'),
            preserve_default=False,
        ),
    ]
