# Generated by Django 3.2.5 on 2022-01-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_aboutus_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='title2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
