# Generated by Django 3.2.5 on 2022-01-28 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_aboutusteam_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategories',
            name='brief',
        ),
    ]
