# Generated by Django 3.2.5 on 2022-02-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_aboutus_subtitle_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusteam',
            name='serial_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategories',
            name='serial_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
