# Generated by Django 3.2.5 on 2022-02-07 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_client'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='client',
            new_name='Customer',
        ),
    ]
