# Generated by Django 3.2.5 on 2022-02-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_rename_client_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest_Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=254, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=254, null=True)),
                ('requirement', models.CharField(blank=True, max_length=254, null=True)),
                ('message', models.CharField(blank=True, max_length=554, null=True)),
            ],
        ),
    ]
