# Generated by Django 3.2.5 on 2022-02-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_interest_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_page_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='HomeVideo')),
            ],
        ),
    ]
