# Generated by Django 4.0.2 on 2022-02-16 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_home_page_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='our_work')),
                ('heading1', models.CharField(blank=True, max_length=50, null=True)),
                ('heading2', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='work')),
                ('image_mobile', models.FileField(blank=True, null=True, upload_to='work')),
            ],
        ),
        migrations.CreateModel(
            name='ourworks_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('brief', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='our_work')),
                ('video_link', models.CharField(max_length=100)),
                ('works', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='home.work')),
            ],
        ),
    ]
