# Generated by Django 4.0.2 on 2022-02-18 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_ourworks_video_serial_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ourworks_video',
        ),
    ]
