# Generated by Django 4.0.2 on 2022-02-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_delete_ourworks_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='heading',
            field=models.TextField(blank=True, null=True),
        ),
    ]
