# Generated by Django 4.0.2 on 2022-02-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_aboutus_youtube_title_alter_aboutus_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_us_youtube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('brief', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_us_youtube')),
                ('video_link', models.CharField(max_length=100)),
                ('about_us_youtube', models.ManyToManyField(related_name='about_us_youtube', to='home.Aboutus')),
            ],
        ),
    ]
