# Generated by Django 4.0.2 on 2022-02-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_about_us_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='youtube_title_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='youtube_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
