# Generated by Django 4.0.2 on 2022-02-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_aboutus_youtube_title_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='work_youtube_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('brief', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='work_videos')),
                ('video_link', models.CharField(max_length=100)),
            ],
        ),
    ]
