# Generated by Django 4.0.2 on 2022-02-22 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_work_youtube_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='create_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='create_video')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='create_video_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='create_video_image')),
                ('create_video', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='createvideoimage', to='home.create_video')),
            ],
        ),
    ]
