# Generated by Django 4.0.2 on 2022-02-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_contact_us_create_video_image_serial_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_client_logo_and_Vi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_client', models.ImageField(blank=True, null=True, upload_to='Image_client_logo_and_Vi')),
                ('image_VI', models.ImageField(blank=True, null=True, upload_to='Image_client_logo_and_Vi')),
            ],
        ),
    ]
