# Generated by Django 4.0.2 on 2022-02-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0021_categories_brief_youtube1_categories_brief_youtube2_and_more'),
        ('home', '0036_marketplacevideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperCategoryVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=100, null=True)),
                ('title_youtube1', models.CharField(blank=True, max_length=50, null=True)),
                ('brief_youtube1', models.CharField(blank=True, max_length=100, null=True)),
                ('image_youtube1', models.ImageField(blank=True, null=True, upload_to='marketplacevideoimage')),
                ('video_link_youtube1', models.CharField(blank=True, max_length=100, null=True)),
                ('title_youtube2', models.CharField(blank=True, max_length=50, null=True)),
                ('brief_youtube2', models.CharField(blank=True, max_length=100, null=True)),
                ('image_youtube2', models.ImageField(blank=True, null=True, upload_to='marketplacevideoimage')),
                ('video_link_youtube2', models.CharField(blank=True, max_length=100, null=True)),
                ('title_youtube3', models.CharField(blank=True, max_length=50, null=True)),
                ('brief_youtube3', models.CharField(blank=True, max_length=100, null=True)),
                ('image_youtube3', models.ImageField(blank=True, null=True, upload_to='marketplacevideoimage')),
                ('video_link_youtube3', models.CharField(blank=True, max_length=100, null=True)),
                ('supercategory', models.ManyToManyField(related_name='supercategory_video', to='categories.SuperCategory')),
            ],
        ),
    ]
