# Generated by Django 4.0.2 on 2022-02-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_supercategoryvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_client_logo_and_vi',
            name='watch_our_more_work',
            field=models.ImageField(blank=True, null=True, upload_to='watch_our_more_work'),
        ),
        migrations.AddField(
            model_name='image_client_logo_and_vi',
            name='watch_our_more_work_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='watch_our_more_work'),
        ),
    ]
