# Generated by Django 3.2.5 on 2022-03-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_termsandcondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsandcondition',
            name='slug',
            field=models.SlugField(default=None, editable=False),
            preserve_default=False,
        ),
    ]
