# Generated by Django 4.0.2 on 2022-03-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_termsandcondition_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='contact_us',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
