# Generated by Django 4.0.2 on 2022-03-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_contact_us_location_delete_contact_us_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='creators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='creators')),
                ('textcard1', models.TextField(blank=True, null=True)),
                ('textcard2_heading', models.CharField(blank=True, max_length=254, null=True)),
                ('textcard2', models.TextField(blank=True, null=True)),
                ('textcard3_heading_black', models.CharField(blank=True, max_length=254, null=True)),
                ('textcard3_heading_blue', models.CharField(blank=True, max_length=254, null=True)),
                ('textcard3', models.TextField(blank=True, null=True)),
                ('video1', models.FileField(blank=True, null=True, upload_to='creators')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='creators')),
                ('text_heading_black1', models.CharField(blank=True, max_length=254, null=True)),
                ('text_heading_blue', models.CharField(blank=True, max_length=254, null=True)),
                ('text_heading_black2', models.CharField(blank=True, max_length=254, null=True)),
                ('image3', models.ImageField(blank=True, null=True, upload_to='creators')),
                ('textcard4', models.TextField(blank=True, null=True)),
                ('heading_black', models.CharField(blank=True, max_length=254, null=True)),
                ('heading_blue', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('video2', models.ImageField(blank=True, null=True, upload_to='creators')),
            ],
        ),
    ]
