# Generated by Django 4.0.2 on 2022-03-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_creators'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creators',
            old_name='text_heading_blue',
            new_name='text_heading_blue1',
        ),
        migrations.AddField(
            model_name='creators',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='creators'),
        ),
        migrations.AddField(
            model_name='creators',
            name='text_heading_blue2',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='creators',
            name='textcard5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
