# Generated by Django 4.0.2 on 2022-03-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_rename_text_heading_blue_creators_text_heading_blue1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creators',
            name='text_heading_black_1',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
