# Generated by Django 4.0.2 on 2022-03-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_creators_text_heading_black_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='creators',
            name='text_heading_black_2',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
