# Generated by Django 4.0.2 on 2022-03-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_creators_text_heading_black_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creators',
            old_name='heading_black',
            new_name='heading4',
        ),
        migrations.RenameField(
            model_name='creators',
            old_name='heading_blue',
            new_name='heading4_blue4',
        ),
        migrations.AddField(
            model_name='creators',
            name='heading_black3',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='creators',
            name='heading_blue3',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='creators',
            name='image_logo_bottum',
            field=models.ImageField(blank=True, null=True, upload_to='creators'),
        ),
        migrations.AddField(
            model_name='creators',
            name='text',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='creators',
            name='video3',
            field=models.ImageField(blank=True, null=True, upload_to='creators'),
        ),
        migrations.AddField(
            model_name='creators',
            name='video4',
            field=models.ImageField(blank=True, null=True, upload_to='creators'),
        ),
        migrations.AddField(
            model_name='creators',
            name='video5',
            field=models.ImageField(blank=True, null=True, upload_to='creators'),
        ),
        migrations.AddField(
            model_name='creators',
            name='video6',
            field=models.ImageField(blank=True, null=True, upload_to='creators'),
        ),
        migrations.AddField(
            model_name='creators',
            name='video7',
            field=models.ImageField(blank=True, null=True, upload_to='creators'),
        ),
        migrations.AddField(
            model_name='creators',
            name='video8',
            field=models.ImageField(blank=True, null=True, upload_to='creators'),
        ),
        migrations.AddField(
            model_name='creators',
            name='video_bottum',
            field=models.FileField(blank=True, null=True, upload_to='creators'),
        ),
    ]
