# Generated by Django 4.0.2 on 2022-03-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_rename_heading_black_creators_heading4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creators',
            name='video9',
            field=models.FileField(blank=True, null=True, upload_to='creators'),
        ),
        migrations.AlterField(
            model_name='creators',
            name='video2',
            field=models.FileField(blank=True, null=True, upload_to='creators'),
        ),
        migrations.AlterField(
            model_name='creators',
            name='video3',
            field=models.FileField(blank=True, null=True, upload_to='creators'),
        ),
        migrations.AlterField(
            model_name='creators',
            name='video4',
            field=models.FileField(blank=True, null=True, upload_to='creators'),
        ),
        migrations.AlterField(
            model_name='creators',
            name='video5',
            field=models.FileField(blank=True, null=True, upload_to='creators'),
        ),
        migrations.AlterField(
            model_name='creators',
            name='video6',
            field=models.FileField(blank=True, null=True, upload_to='creators'),
        ),
        migrations.AlterField(
            model_name='creators',
            name='video7',
            field=models.FileField(blank=True, null=True, upload_to='creators'),
        ),
        migrations.AlterField(
            model_name='creators',
            name='video8',
            field=models.FileField(blank=True, null=True, upload_to='creators'),
        ),
    ]
