# Generated by Django 4.0.2 on 2022-03-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_creators_video9_alter_creators_video2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creators',
            name='video2',
        ),
        migrations.RemoveField(
            model_name='creators',
            name='video3',
        ),
        migrations.RemoveField(
            model_name='creators',
            name='video4',
        ),
        migrations.RemoveField(
            model_name='creators',
            name='video5',
        ),
        migrations.RemoveField(
            model_name='creators',
            name='video6',
        ),
        migrations.RemoveField(
            model_name='creators',
            name='video7',
        ),
        migrations.RemoveField(
            model_name='creators',
            name='video8',
        ),
        migrations.RemoveField(
            model_name='creators',
            name='video9',
        ),
        migrations.AddField(
            model_name='creators',
            name='video_image2',
            field=models.ImageField(blank=True, null=True, upload_to='creators'),
        ),
        migrations.AddField(
            model_name='creators',
            name='video_image3',
            field=models.ImageField(blank=True, null=True, upload_to='creators'),
        ),
        migrations.AddField(
            model_name='creators',
            name='video_image4',
            field=models.ImageField(blank=True, null=True, upload_to='creators'),
        ),
        migrations.AddField(
            model_name='creators',
            name='video_image5',
            field=models.ImageField(blank=True, null=True, upload_to='creators'),
        ),
        migrations.AddField(
            model_name='creators',
            name='video_image6',
            field=models.ImageField(blank=True, null=True, upload_to='creators'),
        ),
        migrations.AddField(
            model_name='creators',
            name='video_image7',
            field=models.ImageField(blank=True, null=True, upload_to='creators'),
        ),
    ]
