# Generated by Django 4.0.2 on 2022-03-08 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_remove_creators_video2_remove_creators_video3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creators',
            name='heading4',
        ),
        migrations.RemoveField(
            model_name='creators',
            name='heading4_blue4',
        ),
        migrations.RemoveField(
            model_name='creators',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='creators',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='creators',
            name='text',
        ),
        migrations.RemoveField(
            model_name='creators',
            name='text_heading_black1',
        ),
        migrations.RemoveField(
            model_name='creators',
            name='text_heading_black2',
        ),
        migrations.RemoveField(
            model_name='creators',
            name='text_heading_black_1',
        ),
        migrations.RemoveField(
            model_name='creators',
            name='text_heading_black_2',
        ),
        migrations.RemoveField(
            model_name='creators',
            name='text_heading_blue1',
        ),
        migrations.RemoveField(
            model_name='creators',
            name='text_heading_blue2',
        ),
        migrations.RemoveField(
            model_name='creators',
            name='textcard4',
        ),
    ]
