# Generated by Django 4.0.2 on 2022-03-08 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_remove_creators_heading4_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creators',
            old_name='heading_black3',
            new_name='heading_black',
        ),
        migrations.RenameField(
            model_name='creators',
            old_name='heading_blue3',
            new_name='heading_blue',
        ),
        migrations.RemoveField(
            model_name='creators',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='creators',
            name='textcard5',
        ),
    ]
