# Generated by Django 4.0.4 on 2022-04-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest_person',
            name='message',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
