# Generated by Django 4.0.4 on 2022-04-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_alter_interest_person_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest_person',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
