# Generated by Django 4.0.4 on 2022-04-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_alter_interest_person_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='project_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='reference_link',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
