# Generated by Django 3.2.5 on 2022-05-17 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0025_delete_metatags'),
        ('home', '0054_alter_customer_project_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_name', models.CharField(max_length=254)),
                ('meta_description', models.TextField()),
                ('categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='categories.categories')),
                ('subcategories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.subcategories')),
            ],
        ),
    ]
