# Generated by Django 2.2.12 on 2021-12-28 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0004_categories_super_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=254)),
                ('video_name', models.CharField(max_length=254)),
                ('video_link', models.CharField(max_length=254)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('super_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categories.SuperCategory')),
            ],
        ),
    ]
